version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  app:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - MONGO_HOST=mongodb://mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=cars
      - API_KEY=test1234
    ports:
      - '3000:3000'
