### Create a new car
POST http://localhost:3000/api/cars
content-type: application/json
x-api-key: test1234

{
    "model": "corolla",
    "brand": "toyota",
    "make": "2019",
    "color": "white",
    "mileage": 1000
}

### Get car by id
GET http://localhost:3000/api/cars/620037ac2be24d2070fdaa2d
x-api-key: test1234

### Get all cars
GET http://localhost:3000/api/cars
x-api-key: test1234


### Delete a car with a given id
DELETE http://localhost:3000/api/cars/620003a663d7b0282b5d6554
x-api-key: test1234

### Update a car with a given id
PATCH http://localhost:3000/api/cars/620003a663d7b0282b5d6554
content-type: application/json
x-api-key: test1234

{
    "color": "blue"
}